// Regenerates docs/EVENTS.md from the event schema files.
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const eventsDir = path.join(root, "schema", "events");
const docsDir = path.join(root, "docs");
fs.mkdirSync(docsDir, { recursive: true });

const classes = ["auto_collected", "enhanced_measurement", "ecommerce", "recommended"];
const byClass = Object.fromEntries(classes.map((c) => [c, []]));

for (const f of fs.readdirSync(eventsDir).filter((f) => f.endsWith(".json")).sort()) {
  const s = JSON.parse(fs.readFileSync(path.join(eventsDir, f), "utf8"));
  byClass[s["x-event-class"]].push(s);
}

let md = "# Events\n\nGenerated by `scripts/generate-docs.js`. Do not edit by hand.\n";
for (const c of classes) {
  md += `\n## ${c}\n\n| Event | Required | Description |\n|---|---|---|\n`;
  for (const s of byClass[c]) {
    const req = (s.required || []).filter((r) => r !== "event").join(", ") || "—";
    md += `| [\`${s.title}\`](../schema/events/${s.title}.json) | ${req} | ${s.description} |\n`;
  }
}
fs.writeFileSync(path.join(docsDir, "EVENTS.md"), md);
console.log("docs/EVENTS.md written");
